language: python
python:
  - "3.7"
install:
  - pip install -r python/requirements.txt
  - pip install -e python/.
  - pip install pytest-cov codecov
script:
  - pytest --cov=python/src python/tests
after_success:
  - codecov
